[package]
name = "sonos"
version = "0.1.0"
authors = ["Matt Jones <jonesmr@gmail.com>"]
edition = "2018"

[dependencies]
actix-session = "0.1.0-beta.1"
actix-web = "1.0.0-beta.1"
oauth2 = "2.0.0-beta.2"
url = "*"
